var vocabulario = ["TORNADO","EARTHQUAKE","BLIZZARD","TSUNAMI","HURRIACANE",
 "FLOD","ERUPTION","AVALANCHE","LANDSLIDE","DROUGHT","WILDFIRE",
 "THUNDERSTORM","CYCLONE","WHIRLWIND","SANDSTORM","HAILSTORM"]
